app/urls.py
from django.urls import path
from . import views


app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('contractor_cabinet/', views.contractor_cabinet, name='customers'),
    path('customer_cabinet/', views.customer_cabinet, name='contractors'),
    path('contractor/<int:customer_id>', views.single_customer, name='single_customer'),
    path('customer/<int:customer_id>', views.single_contractor, name='single_contractor')
]

base/urls.py
from django.contrib import admin
from django.urls import path, include


app_name = 'base'
urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('app.urls'))
]

app/models.py
from django.db import models


class Customer(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    experience = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Contractor(models.Model):
    name = models.CharField(max_length=255)
    phone_number = models.IntegerField()
    experience = models.CharField(max_length=255)

    def __str__(self):
        return self.name

app/views.py
from django.shortcuts import render, get_object_or_404
from .models import Customer, Contractor


def index(request):
    return render(request, 'app/menu.html')


def contractor_cabinet(request):
    customers = Customer.objects.all()
    return render(request, 'app/customers.html', {'customers': customers})


def customer_cabinet(request):
    contractors = Contractor.objects.all()
    return render(request, 'app/contractors.html', {'contractors': contractors})


def single_customer(request, customer_id):
    customer = get_object_or_404(Customer, pk=customer_id)
    return render(request, 'app/single_customer.html', {'customer': customer})


def single_contractor(request, contractor_id):
    contractor = get_object_or_404(Contractor, pk=contractor_id)
    return render(request, 'app/contractor.html', {'contractor': contractor})

templates/app/contractors.html
{% extends 'base.html' %}

{% block title %}Contractors{% endblock %}

{% block content %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<table class="table mt-5 table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Phone number</th>
            <th>Experience</th>
        </tr>
    </thead>
    <tbody>
        {% for contractor in contractors %}
        <tr>
            <td>
                <a href={% url "app:single_contractor" contractor.id %}>{{ contractor.name }}</a>
            </td>
            <td>{{ contractor.phone_number}}</td>
            <td>{{ contractor.experience }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/app/customers.html
{% extends 'base.html' %}

{% block title %}Customers{% endblock %}

{% block content %}
<head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<table class="table mt-5 table-striped table-hover">
    <thead class="table-dark">
        <tr>
            <th>Name</th>
            <th>Phone number</th>
            <th>Experience</th>
        </tr>
    </thead>
    <tbody>
        {% for customer in customers %}
        <tr>
            <td>
                <a href={% url "app:single_customer" customer.id %}>{{ customer.name }}</a>
            </td>
            <td>{{ customer.phone_number}}</td>
            <td>{{ customer.experience }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/app/menu.html
{% extends 'base.html' %}

{% block title %}Main menu{% endblock %}

{% block content %}
<h1 class="mt-5">Hello!/ Привет!</h1>
<h2>Используйте верхнюю панель для навигации</h2>
{% endblock %}

templates/app/single_contractor.html
{% extends 'base.html' %}

{% block title %}{{ contractor.title }}{% endblock %}

{% block content %}
<h1 class="mt-5" >{{ contractor.name }}</h1>
<h2>Phone number: {{ contractor.phone_number }}</h2>
<p>Experience: {{ contractor.experience }}</p>
{% endblock %}

templates/app/single_customer.html
{% extends 'base.html' %}

{% block title %}{{ customer.title }}{% endblock %}

{% block content %}
<h1 class="mt-5" >{{ customer.name }}</h1>
<h2>Phone number: {{ customer.phone_number }}</h2>
<p>Experience: {{ customer.experience }}</p>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <div class="container">
          <a href={% url "app:index" %} class="navbar-brand">Site</a>
          <span class="navbar-text">
              <a href={% url "app:customers" %} class="me-2">Contractor cabinet</a>
              <a href={% url "app:contractors" %} class="me-2">Customer cabinet</a>
              <a href="/admin/" class="me-2" target="_blank">Admin</a>
          </span>
        </div>
    </nav>
    <main class="container">
        {% block content %}
        {% endblock %}
    </main>
</body>
</html>